### ISSUE TITLE
Function keys (F1-F12) not working

### ISSUE THREAD

**Issue by cacilhas** [raphamorim/rio#1225]
Rio isn’t able to detect function keys (F1, F2, F3, F4…).

Even more bizarre, no application launched from Rio is!

I launched `xev -event keyboard` from other terminals, and it can detect function keys normally. However, when I launched it from Rio, function keys are completely ghosted, like those keys doesn’t exist or wasn’t detected by the system.

```sh
❯ rio --version
rioterm 0.2.21
❯ uname -a
Linux dream 6.6.56-1-lts #1 SMP PREEMPT_DYNAMIC Thu, 10 Oct 2024 12:04:53 +0000 x86_64 GNU/Linux
```

My system is an Arch Linux, and Rio was installed by `cargo`:

```sh
cargo install --git=https://github.com/raphamorim/rio.git rioterm
```

**Comment by raphamorim** [comment]
was it working well on v0.2.20 or 0.2.19? i wonder if is the cap protocol was introduced on those versions

**Comment by cacilhas** [comment]
No, I remember to check function keys on v0.2.20, and it was already not working then.

**Comment by cacilhas** [comment]
No, I remember to check function keys on v0.2.20, and it was already not working then. I dunno whether it was working or not on v0.2.19 though.

**Comment by cacilhas** [comment]
I have ibus running to manage my keyboard. Does Rio have any interaction with ibus?

**Comment by raphamorim** [comment]
Hey @cacilhas could you check with latest? if does work will look for next version. My guess was it was an ime issue fixed in .2.25

**Comment by cacilhas** [comment]
@raphamorim it actually now got worse: `xev` is no longer able to show any key when launched by `rio`, and function keys are still not usable from config file.

It’s still working in Neovim though.

**Comment by raphamorim** [comment]
partial progress in #1717: f1 to f20 can now be used in [bindings] (they were rejected by the config parser before). the deeper issue of keys not being detected at all with ibus is still open, can you retest on 0.4.11?
