### ISSUE TITLE
New keybinding for SplitDown and SplitRight do not work on Windows

### ISSUE THREAD

**Issue by zoof** [raphamorim/rio#1288]
I added:
```
[bindings]
keys =[
	{ key = "d", with = "control | alt", action="SplitDown"},
	{ key = "r", with = "control | alt", action="SplitRight"},
	{ key = "tab", with = "control", action="SelectNextSplitOrTab"}
]
```
to config.toml file.  While the last bind to switch splits or tabs works, the first two do not.  I haven't experimented with Linux much yet, but my recollection is that the first two worked on the Flatpak installation of rio on a BlueFin Linux installation.

**Comment by olaf-rogalsky** [comment]
possibly related to #1275

**Comment by zoof** [comment]
I assume that you mean I should compile main from the repo?  I only use the windows version on my work laptop and am not allowed to install a rust compiler.  It does not work with release 0.2.35.

**Comment by raphamorim** [comment]
Should be working with v0.4.12 thank you!

**Comment by zoof** [comment]
I just tried 0.5.0 and it is still not working for me.  As before, the final bind will switch splits but the former two do not create splits.
