### ISSUE TITLE
Mouse selection is off by a few characters

### ISSUE THREAD

**Issue by Stupremee** [raphamorim/rio#386]
Hey,

I've just started using Rio, and am really happy. Except one thing. Whenever I use my mouse to select something, the selection is always of by one or even more characters. 

I'm using the new GitHub Monaspace Font, which I would like to keep, so I hope this can be fixed.

https://github.com/raphamorim/rio/assets/39732259/9d40dfdd-89d1-46ce-962e-f286bf09422a

https://github.com/raphamorim/rio/assets/39732259/b83066f4-d1d7-466e-8c0e-3841c4c234a9

**Comment by RaySlash** [comment]
@Stupremee  the videos looks corrupted. Do you have any kind of scaling turned on? I reckon you can post your configuration for better clarity here. Cheers!

**Comment by Stupremee** [comment]
Hi @RaySlash 

That's weird because the videos work for me. I will try to upload new ones here.

https://github.com/raphamorim/rio/assets/39732259/13ba2066-6d37-4323-baae-53b302bd1242

This is my Rio Terminal config: https://paste.rs/1h3fi

**Comment by RaySlash** [comment]
@Stupremee videos are still broken or is that how u see. All I see is this:
![Screenshot_20231216-163928](https://github.com/raphamorim/rio/assets/45141270/7ff05095-0d33-40b6-8687-0da673fe4fbc)

Black bg with some grain like pixels.

**Comment by ralgozino** [comment]
FWIW videos are working for me (chrome+macos)
<img width="933" alt="image" src="https://github.com/raphamorim/rio/assets/6362698/18f6938f-6929-4cb8-b3e5-7a7428f99c69">

Regarding text selection, it is working better than in previous versions but it still needs some work, I believe it is related to the font rendering issues.

**Comment by Lattay** [comment]
Hi,

The problem does not only concerns the selection, but all mouse interactions. It also depends on the size of the font and increases with the distance to the top left corner. As such I think it is a problem of converting screen coordinates into grid coordinates that does not properly consider the size of a character in the current font.

**Comment by raphamorim** [comment]
Hey there! thanks for the issue, this should be gone (fixed by #374). Please let me know anything!

**Comment by hadim** [comment]
I am still seeing this issue but relative to the y-axis in my case. I opened a new ticket at https://github.com/raphamorim/rio/issues/823
