### ISSUE TITLE
[Bug] Text Rendering Bug

### ISSUE THREAD

**Issue by arjpar** [raphamorim/rio#543]
As described in the Rio Discord, this text rendering bug messes up all (many of?) the glyphs in Rio. I'm not sure what the steps to reproduce are. @raphamorim said that it could be that the glyph cache is using the wrong font id to render.

Example:
![image](https://github.com/raphamorim/rio/assets/41452613/e14e5df4-1a10-4ded-a774-feaf52834072)

**Comment by TitanNano** [comment]
I have a similar issue in helix. Some characters get completely messed up.

Here, the default nushell env config:
<img width="1698" alt="Screenshot 2024-06-12 at 23 48 30" src="https://github.com/raphamorim/rio/assets/4500858/8fc7451b-e1b6-4a1e-9336-7c9300c66264">

**Comment by raphamorim** [comment]
I believe that this issue is fixed  in the v0.1.2 or at least I fixed what I was able to reproduce. The cause was that outdated epochs that were being deleted glyphs from atlas and in the next renderer were being quite odd/weird.

**Comment by TitanNano** [comment]
@raphamorim I can still reproduce some text rendering issues.

https://github.com/user-attachments/assets/b869e64b-7d33-4ca4-b624-3b5d21208038

I think it has something to-do with text colors as you can see that depending on the selected theme the issues move.

**Comment by arjpar** [comment]
I can also reproduce text rendering issues using helix that aren't present on other terminal emulators.
<img width="875" alt="image" src="https://github.com/user-attachments/assets/d740138b-4ded-4ceb-993b-28049d1514d2">

**Comment by raphamorim** [comment]
Thanks folks for testing it! Will be looking, @TitanNano I couldn't play your video 😢

**Comment by TitanNano** [comment]
@raphamorim I replaced the screencap with an MP4 version, hopefully that works better for you.

**Comment by raphamorim** [comment]
perfect! thank you

**Comment by raphamorim** [comment]
Pushed a fix for it in main, would you mind test?

Before
<img width="512" alt="Screenshot 2024-08-04 at 23 37 51" src="https://github.com/user-attachments/assets/b7e7acb3-3c7e-4ab1-9228-14389e4b032e">

After
<img width="596" alt="Screenshot 2024-08-04 at 23 37 18" src="https://github.com/user-attachments/assets/a07eb44c-f9a7-4ddd-89c5-61f99e19170a">

**Comment by TitanNano** [comment]
@raphamorim I can no longer reproduce the bug with the latest master.

**Comment by raphamorim** [comment]
That's great! Thanks for testing!
